#
# Module manifest for module 'MiniUtilPS'
#
# Generated by: Chun Pan Yung
#
# Generated on: 3/18/2024
#

@{

# Script module or binary module file associated with this manifest.
# RootModule = ''

# Version number of this module.
ModuleVersion = '0.0.1'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = '822afcf0-c1cc-4436-8385-0547aea5ae3e'

# Author of this module
Author = 'Chun Pan Yung'

# Copyright statement for this module
Copyright = '(c) Chun Pan Yung. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Contains various utilities functions and scripts for self use.'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '7.4'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = "Get-SoftwareName", "Initialize-MauiDev", "Install-SSH"

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/ChunPanYung/MiniUtilPS'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        # ReleaseNotes = ''

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

} # End of PrivateData hashtable
}
